title = 'ゴールデンウィークが終わる 2026'
categories = ['雑記']
content = '''
みんなゴールデンウィークどうだった？　仕事だった？　おつかれさまです

あたくしはとりあえずスターレイルの開拓クエスト（メインストーリー）を最新のまでやりきったわよ

おもしろかった

おわり

### おまけ

なんか最近無限にやる気なかったためいろいろやることを減らして最低限度の生活をしていたんだけれど

ちょっとだけがんばってなにかしたい

ねこのしり先生を応援しよう
'''
