title = '大人'
categories = ['雑記', 'ゲーム']
content = '''
ごきげんよう

このブログをみてくれているみんなはなんとなくわかるとおもうけれど

あたくしはいい歳して

がきんちょ！！！！！！！！！！！！！！！！！！！！！！！！

どうやったら大人になれる？

てか大人ってなに？

ってずっと思ってるけれど

最近ちょっとだけ思ったのは

若者のために責任をとれるのが大人ってやつなのかもしれない

### ムジュラの仮面

大人で思い出すのはやっぱり『ゼルダの伝説 ムジュラの仮面』

このゲームに出てくる大人たちは

えらそうだったり優柔不断だったり

頼りなさそうだったりするわけだけど

その時がくればみんな

大人の責任を果たしてくれる

いや

そうだっけ？

とりあえず

子どもと大人というテーマについてよく描かれているゲームですわよ

### まとめ

大人とはなんであるかということについて

みんないろいろ好き勝手言うけれど

でもそういうことを考えることで

大人として生きていくという覚悟ができるのかもしれない

てか

ムジュラの仮面の話するのもう３回目くらいかもしれない

ほんとうに好きなゲームなのでゆるして

子どものころやったゲームの話を一生し続けるがきんちょがよ～
'''
