title = '生活マン'
categories = ['雑記', '漫画']
content = '''
ごきげんよう

ねこしりだ

生活マン

あんたは

生活マン読んだことあるか

<figure>
  <a href="https://www.amazon.co.jp/dp/B0GR3TMJQF">
    <img src="https://m.media-amazon.com/images/I/716atVAgUxL._SL1200_.jpg" alt="" width="200" />
    <figcaption>生活マン 1 (ジャンプコミックスDIGITAL)</figcaption>
  </a>
</figure>

読め

なんなら

ジャンプルーキー掲載のプロトタイプ版（？）でもいい

[生活マン - ジャンプルーキー！](https://rookie.shonenjump.com/series/zGZPbQ8vsbk)

生活マン

なんだこれは

生活パーソンにしろ

おい

おれは

生活マンになりたい

おれの夢は

生活マン

あと

原作者の X は

見なくていい
'''
