title = '結婚'
categories = ['雑記']
content = '''
ごきげんよう

今日は

なぜか早朝に起きてしまったので

あたくしがいつも避けている話題について

早朝テンションで書くわよ

あたくしはもういい年なので

そろそろ結婚しないと間に合わない

かもしれないし

そんなことないかもしれない

結婚相談所に駆け込むなら

はやいほうがいい

ってのはわかってるんだけれど

まあまだぎり大丈夫だから……

と思っていくのをさけている

がきんちょ！！！！！！！！！！！！！！！！！！！！！！！！

ちょっと前までは

別に結婚とかしなくてもよくないかと思ってたんだけれど

一生一人で暮らすことを考えると

やっぱりしたほうがいい気がする

一方で

結婚ってそんな目的でするもんなのか？

とも思う

できないのにそんなこと考えてもしょうがないわよ

人生は

ままならないけれど

ママにもパパにもなれないってな笑

それやめてね

みんなも

ねこのしり先生を

応援してもいいし

しなくてもいい

これはあたくしの人生だから
'''
