title = '酒'
categories = ['雑記']
content = '''
ごきげんよう

ねこしりですわよ

みんなはお酒飲む？

あ

20 歳未満はのんじゃだめですわよ

あたくしは

そんなに飲まないけれど

会津には酒蔵がたくさんあって

おいしい日本酒がいっぱいあるんですわよ

有名なところだと「冩樂」とか「飛露喜」とかはあたくしでも知っておりますわ

ほかにも「会津娘」とかかわいい名前のやつもありますわ～

せっかく地元においしいお酒があるんだから

いろいろ飲んでみたいですわよね

そういえば

このまえ曙酒造の「スノードロップ」っていう日本酒ベースのヨーグルトリキュールを飲みましたけれど

甘くて飲みやすいので

日本酒が苦手な場合はこういうのもおすすめかもですわ～

### ねこみみよっぱ事件

あたくしは昔のみすぎてよっぱになって

ねこみみをつけたまま山手線にのって

池袋で落として

駒込あたりで気づいて

戻って探したら

奇跡的に見つかったんですけれど

踏まれて物故割れてましたわ～

いまでも残ってますわよ

このかなしい話以降

あんまりよっぱになるまで飲まなくなりましたわ～

この話は

飲み会とかでするとうけるけど

のみすぎは

よくないですわよ～

ほんとに

みんなも

気をつけなはれや

<figure>
  <a href="https://www.amazon.co.jp/gp/product/B00A2MCPL8">
    <img src="https://m.media-amazon.com/images/I/7131vMTbdnL._SL1024_.jpg" alt="" width="200" />
    <figcaption>夏子の酒（１） (モーニングコミックス)</figcaption>
  </a>
</figure>
'''
