title = 'カメムシ'
categories = ['雑記', '虫']
content = '''
カメムシきらい

すぐ家の中にはいってくるし

くさいから

くさくなければまだかわいげがある気がする～

といっても

あたくしの家は山の中ではないから

まだマシで

そんなにいっぱいいるわけじゃない

でもやだ

<blockquote class="twitter-tweet"><p lang="ja" dir="ltr">おきたら部屋にカメムシがいっぱいいるしトイレにも風呂にも変なムシがいるし洗面所にも謎の虫がいるからうわ〜〜〜〜〜ってなってたらいつもの世界じゃなくて暗黒世界（ダークワールド）だった。</p>&mdash; ねこのしり (@CyLomw) <a href="https://twitter.com/CyLomw/status/1362168113270190089?ref_src=twsrc%5Etfw">February 17, 2021</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet"><p lang="ja" dir="ltr">カメムシに起こされてこれ <a href="https://t.co/p7ucby4yze">https://t.co/p7ucby4yze</a></p>&mdash; ねこのしり (@CyLomw) <a href="https://twitter.com/CyLomw/status/1441192801924902925?ref_src=twsrc%5Etfw">September 24, 2021</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet"><p lang="ja" dir="ltr">今週だけでいえにカメムシ３匹出てるんだけどどうなってる？</p>&mdash; ねこのしり (@CyLomw) <a href="https://twitter.com/CyLomw/status/1839296697983492186?ref_src=twsrc%5Etfw">September 26, 2024</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet"><p lang="ja" dir="ltr">カメムシ発生しはじめてて泣</p>&mdash; ねこのしり (@CyLomw) <a href="https://twitter.com/CyLomw/status/2052561916359483858?ref_src=twsrc%5Etfw">May 8, 2026</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

去年はじめてサシガメを見つけた

レア

でもさされるとちょお痛いらしいからやだ

<blockquote class="twitter-tweet"><p lang="ja" dir="ltr">へやにオオトビサシガメみたいなのいる！</p>&mdash; ねこのしり (@CyLomw) <a href="https://twitter.com/CyLomw/status/1975545091218604518?ref_src=twsrc%5Etfw">October 7, 2025</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

カメムシのなかまはおおすぎる

おれたちの世界は

カメムシに侵略されている

一体いつから

おれたちの世界だと錯覚していた？
'''
