title = 'おジャ魔女どれみの TV アニメーションをぜんぶみた'
categories = ['雑記', 'アニメ']
content = '''
『おジャ魔女どれみ』シリーズの TV アニメーション作品（第１～第４シリーズの計 201 話）が [東映の YouTube チャンネル](https://www.youtube.com/@toeianime_MC) で毎週１話ずつ配信されてたのですけれど

このたびついに最終話が配信されたので

これで全部みたことになる

長かった～（追記：OVA 13 話も配信するらしい）

いちおう女児向けアニメ枠ですけれど

おとなが見てもふつうに面白い

10 話に一回くらいガチ泣きの回が存在していて

見ると絶対に泣いてしまいます

あと個人的に

第２シリーズ 『おジャ魔女どれみ♯』でロイヤルパトレーヌとかいう違法戦力が登場してとつぜんガチ魔法バトルおっぱじめるところも地味に好き

### あたくしとおジャ魔女どれみ

あたくしは田舎生まれ田舎育ちなので

アニメはがきんちょの見るものだし

女児アニメは女児のがきんちょ以外は見てはいけないものだったので

実際にテレビで見ることはほとんどありませんでしたわよ

でもこれで

カラオケでも遠慮なく歌うことができますわね

<iframe width="560" height="315" src="https://www.youtube.com/embed/BWG_OOCRoQo?si=hnubkxZJRtvhmHVY" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>

というか

「おジャ魔女カーニバル!!」がとくに人気ある気がするけれど

「DANCE! おジャ魔女」とか他シリーズの主題歌もめちゃいい

みんなは

どれが好き？

<figure>
  <a href="https://www.amazon.co.jp/dp/B0GWHZ93JC">
    <img src="https://m.media-amazon.com/images/I/611Q7Y5GpKL._SL500_.jpg" alt="" width="200" />
    <figcaption>も～っと！おジャ魔女どれみ　カエル石のひみつ</figcaption>
  </a>
</figure>
'''
